const countryData = [
    { name: "USA", dial_code: "+1", flag: "🇺🇸" },
    { name: "Canada", dial_code: "+1", flag: "🇨🇦" },
    { name: "UK", dial_code: "+44", flag: "🇬🇧" },
    { name: "Australia", dial_code: "+61", flag: "🇦🇺" },
    { name: "India", dial_code: "+91", flag: "🇮🇳" },
    { name: "Germany", dial_code: "+49", flag: "🇩🇪" },
    { name: "France", dial_code: "+33", flag: "🇫🇷" },
    { name: "Italy", dial_code: "+39", flag: "🇮🇹" },
    { name: "Spain", dial_code: "+34", flag: "🇪🇸" },
    { name: "Mexico", dial_code: "+52", flag: "🇲🇽" },
    { name: "Brazil", dial_code: "+55", flag: "🇧🇷" },
    { name: "Japan", dial_code: "+81", flag: "🇯🇵" },
    { name: "China", dial_code: "+86", flag: "🇨🇳" },
    { name: "South Korea", dial_code: "+82", flag: "🇰🇷" },
    { name: "Russia", dial_code: "+7", flag: "🇷🇺" },
    { name: "South Africa", dial_code: "+27", flag: "🇿🇦" },
    { name: "Egypt", dial_code: "+20", flag: "🇪🇬" },
    { name: "Argentina", dial_code: "+54", flag: "🇦🇷" },
    { name: "Chile", dial_code: "+56", flag: "🇨🇱" },
    { name: "Colombia", dial_code: "+57", flag: "🇨🇴" },
    { name: "Peru", dial_code: "+51", flag: "🇵🇪" },
    { name: "Venezuela", dial_code: "+58", flag: "🇻🇪" },
    { name: "Thailand", dial_code: "+66", flag: "🇹🇭" },
    { name: "Vietnam", dial_code: "+84", flag: "🇻🇳" },
    { name: "Malaysia", dial_code: "+60", flag: "🇲🇾" },
    { name: "Philippines", dial_code: "+63", flag: "🇵🇭" },
    { name: "Indonesia", dial_code: "+62", flag: "🇮🇩" },
    { name: "Singapore", dial_code: "+65", flag: "🇸🇬" },
    { name: "New Zealand", dial_code: "+64", flag: "🇳🇿" },
    { name: "Turkey", dial_code: "+90", flag: "🇹🇷" },
    { name: "Saudi Arabia", dial_code: "+966", flag: "🇸🇦" },
    { name: "United Arab Emirates", dial_code: "+971", flag: "🇦🇪" },
    { name: "Nigeria", dial_code: "+234", flag: "🇳🇬" },
    { name: "Kenya", dial_code: "+254", flag: "🇰🇪" },
    { name: "Ghana", dial_code: "+233", flag: "🇬🇭" },
    { name: "Morocco", dial_code: "+212", flag: "🇲🇦" },
    { name: "Algeria", dial_code: "+213", flag: "🇩🇿" },
    { name: "Portugal", dial_code: "+351", flag: "🇵🇹" },
    { name: "Greece", dial_code: "+30", flag: "🇬🇷" },
    { name: "Sweden", dial_code: "+46", flag: "🇸🇪" },
    { name: "Norway", dial_code: "+47", flag: "🇳🇴" },
    { name: "Denmark", dial_code: "+45", flag: "🇩🇰" },
    { name: "Finland", dial_code: "+358", flag: "🇫🇮" },
    { name: "Netherlands", dial_code: "+31", flag: "🇳🇱" },
    { name: "Belgium", dial_code: "+32", flag: "🇧🇪" },
    { name: "Switzerland", dial_code: "+41", flag: "🇨🇭" },
    { name: "Austria", dial_code: "+43", flag: "🇦🇹" },
    { name: "Poland", dial_code: "+48", flag: "🇵🇱" },
    { name: "Czech Republic", dial_code: "+420", flag: "🇨🇿" },
    { name: "Hungary", dial_code: "+36", flag: "🇭🇺" },
    { name: "Israel", dial_code: "+972", flag: "🇮🇱" },
    { name: "Pakistan", dial_code: "+92", flag: "🇵🇰" },
];

export default countryData;
