name: SonarCloud Scan

# Specify when the workflow should run
on:
  push:
    branches:
      - main   # Run on push to main branch
  pull_request:
    branches:
      - main   # Run on pull request to main branch

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest  # Specifies the type of machine for the job

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      # Step 2: Set up Java (required for SonarCloud analysis)
      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Updated to v3
        with:
          distribution: 'temurin'  # Specify the Java distribution
          java-version: '11'

      # Step 3: Cache SonarCloud dependencies to speed up builds
      - name: Cache SonarCloud packages
        uses: actions/cache@v3  # Updated to v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      # Step 4: Run SonarCloud analysis
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Use the token from GitHub Secrets


        run: |
          sonar-scanner \
            -Dsonar.projectKey=<food-to-factory> \
            -Dsonar.organization=<Food to Factory> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
